### ISSUE TITLE
Mod not working in 1.20.4

### ISSUE THREAD

**Issue by StanByes** [bergerhealer/SmoothCoasters#12]
Hello, the mod can start in 1.20.4, I can use F9 key to enable/disable it but the vision isn't update when I'm in a ride.
I found this error in my client logs :
```
Encountered exception while handling in channel with name "smoothcoasters:hs"
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at net.minecraft.class_2540.release(class_2540.java:1775)
	at net.fabricmc.fabric.impl.networking.payload.RetainedPayload.resolve(RetainedPayload.java:46)
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:98)
	at net.minecraft.class_8673.handler$zfn000$fabric-networking-api-v1$onCustomPayload(class_8673.java:1041)
	at net.minecraft.class_8673.method_52780(class_8673.java)
	at net.minecraft.class_2658.method_53024(class_2658.java:94)
	at net.minecraft.class_2658.method_11054(class_2658.java:32)
	at net.minecraft.class_2600.method_11072(class_2600.java:24)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
SmoothCoasters version : 1.20-v1
Fabric Loader version : 0.14.24-1.20.4
Fabric API version : 0.91.1+1.20.4

Thank's

**Comment by 56738** [comment]
Please try with the latest version of Fabric API ([0.92.1+1.20.4](https://github.com/FabricMC/fabric/releases/tag/0.92.1%2B1.20.4)), that contains a bug fix which looks very similar to your issue.

**Comment by StanByes** [comment]
I'll test it now !

**Comment by StanByes** [comment]
Okay, after a verification about my attachments, it's only the seat which had an issue. Now, we need to enforce the "Choppy!" parameter in TrainCarts which isn't needed before

**Comment by StanByes** [comment]
Hello again, we made some tests and we found that the Choppy!'s mode is a only TrainCarts's feature so it doesn't use SmoothCoasters but we need it to allow our players to enable/disable the rotation mode.

We remade a check with clients parameters :
Fabric Loader : 0.15.3
Fabric API : 0.92.1
SmoothCoasters : 1.20-v1

We're using :
Waterfall : 1.20-R0.2-SNAPSHOT:e927093:560
Paper : git-Paper-379

And we saw that the bug appeared only when we passed to another server through the waterfall, maybe the configuration phase @56738 ?

**Comment by StanByes** [comment]
And we got this message when we go to another server : "
Unknown custom packet payload: smoothcoasters:hs"

**Comment by 56738** [comment]
Seems like the mod was breaking after server switches which use the new configuration phase.

Please try this .jar file: https://ci.mg-dev.eu/job/SmoothCoasters/59/

Thanks!

**Comment by StanByes** [comment]
Thanks you ! I will test this in few minutes and give you a feedback :)

**Comment by StanByes** [comment]
Okay ! I tested you version @56738 , the mod keep working after configuration phase but there's a new issue : The rotation axe seems to be broke because my head follow the cart but in the side of it instead in front it, my mouse speed seems to be increase when the mod is enable.

Idk if we'll view the issue in video but it's the way of my head move inside a cart :
https://github.com/bergerhealer/SmoothCoasters/assets/73603926/2d2f4936-d760-4ac2-b0e1-b6946dc64815

**Comment by 56738** [comment]
That looks like the seat could be rotated incorrectly in the attachment editor. Does it also happen in a simple minecart where you didn't edit any attachments?

**Comment by StanByes** [comment]
I'll try this fast (maybe tomorrow)

**Comment by StanByes** [comment]
My cursor has a bug when the mod is active, he pointed a block but is the block aside that is targeted (first screen). When I do F9 the cursor turn to the targeted block (second screen) and when I do F9 again the cursor come back as the first screen. All of my movement (out of carts) are bug as I move to the position of the real view and not the cursor position
For the view in the train, I also tried with a simple minecart on rails and I got the same issue

**Comment by StanByes** [comment]
![2024-01-21_19 35 30](https://github.com/bergerhealer/SmoothCoasters/assets/73603926/7d5ac8ed-6a16-4bb0-b672-16832d7248f6)
![2024-01-21_19 35 32](https://github.com/bergerhealer/SmoothCoasters/assets/73603926/19c872cb-ad1c-4110-bd92-c87812b54128)

**Comment by StanByes** [comment]
Hey @56738 some ideas ?

**Comment by 56738** [comment]
It could be an incompatibility with another mod.

What's the full list of mods you're using? Does this also happen if only Fabric API and SmoothCoasters are installed?

**Comment by StanByes** [comment]
I'll try with only SmoothCoasters and Fabric API in a few minutes

**Comment by StanByes** [comment]
Okay ! The mod working perfectly when I have only it and Fabric API
I'll try add one per one my mods to find which make a conflict between them

**Comment by StanByes** [comment]
Find ! This is optifabric...

**Comment by 56738** [comment]
Unfortunately, OptiFine is closed source and replaces a lot of the rendering code, so adding compatibility with that would require a lot of time which I currently don't have.

Most people have switched to [Sodium](https://modrinth.com/mod/sodium) (or [Iris Shaders](https://modrinth.com/mod/iris)) since those were made for Fabric and work with other mods.

**Comment by StanByes** [comment]
Okay I'll try with this mod

**Comment by StanByes** [comment]
Iris/Sodium are working perfectly !
Thank's for your help :)
